### PR TITLE
Added interval restart logic

### PR DESCRIPTION
**Pull request by umbreak**
Fixes https://github.com/BlueBrain/nexus/issues/2245
Fixes https://github.com/BlueBrain/nexus/issues/2259

### CODE REVIEW

**Comment by imsdu** [comment]
Something mixing things like:
* IO.timeout so that it stops after a while
* scheduler.scheduleAtFixedRate to start it again
would not work ?

**Comment by umbreak** [comment]
Why do we need to do it that way?
I'm working with `F[_]` so `scheduleAtFixedRate` is not going to fly out.

I don't find this implementation more difficult either.

**Comment by imsdu** [comment]
We could just let the timeout and let the remember entities restart it ? Or use in some way the coordinator.restart ?

It is not this addition that is complicated, it is more that that there is an accumulation with what already exists.

**Comment by umbreak** [comment]
I don't see how any of your suggestions is simpler than what I did. Unless I see some concrete example with some benefits, I'm not confident of the change. And I don't want to touch `IndexingStreamCoordinator`, since it is complex enough already. Management of lifecycle and so on happen on the `CompositeIndexingStream` previously and now. So it is consistent.

 Another option is to put everything inside an actor and keep the nextInterval (Option[Instant]) as the actor state. However I would argue that option is more verbose.

**Pull request closed without merging**
