### PR TITLE
Allow rdf parser to be configurable

### LINKED ISSUE #2760: Invalid IRIs should be properly rejected
Currently when there is a invalid IRI (e.g. that contains a space), no error is returned to the user and the indexing in Blazegraph fails later after a simple log in Delta
```
WARN  org.apache.jena.riot - Bad IRI: < https://doi.org/10.3389/fnsyn.2019.00029> Spaces are not legal in URIs/IRIs.
```
Adding `.checking(true)` to this [line](https://github.com/BlueBrain/nexus/blob/master/delta/rdf/src/main/scala/ch/epfl/bluebrain/nexus/delta/rdf/jsonld/api/JsonLdJavaApi.scala#L68) and/or changing the error handler: https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/riot/RDFParserBuilder.html#checking(boolean)
should help to solve this.

### PR DESCRIPTION
**Pull request by imsdu**
Fixes #2760 

* The rdf parser for validating data can be configured to be more or less strict
* The rdf parser for fetching/indexing remains lenient to be able to return a resource no matter the strictness defined for validation (and also because there is no need to validate them again)

### CODE REVIEW

**Comment by umbreak** [comment]
Yep, checking and strict were the solution.

However your test only handles the case expanded -> Graph, as far as I can see.

Does this also throw when converting compacted -> expanded ?

**Comment by imsdu** [comment]
Nope, nothing is thrown at the expanded/compacted level

**Comment by umbreak** [comment]
Ok. So then as far as I can tell this is not going to solve the root problem, which is: people will still be able to create resources with those "wrong" IRIs (for example iris with a space at the beginning). 
We are just going to get another kind of warning/error.

**Comment by imsdu** [comment]
The problem is solved in my PR, we transform the expanded into a graph in the resources state machine (I only had to add this for resources not validated by a schema, we already did it otherwise)
We get an `InvalidJsonLdFormat` rejection if the iri is wrong

**Review by umbreak — APPROVED** [review]

**Review by bogdanromanx — APPROVED** [review]

**Pull request merged**
